---
# handlers file for 
- name: "Restart Apache"
  service:
    name: httpd
    state: restarted
  when: ansible_distribution == 'CentOS'

- name: "Enable Apache"
  service:
    name: httpd
    enabled: yes
  when: ansible_distribution == 'CentOS'